### ISSUE TITLE
How to grow grape vines from seed? 🌱 🍇 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-permaculture#32]
My favourite grapes are an [Heirloom](https://www.thespruce.com/all-about-heirloom-grapevines-2539921) variety that are increasingly difficult to find/buy because they have seeds.
I have picked and eaten them several times and they immensely flavourful! 

![fox-grapes](https://github.com/dwyl/learn-permaculture/assets/194400/7da5b857-3569-48f0-92e3-5cd1bc12ac77)

In `Portugal` these grapes are colloquially referred to as **`Uva Americana`** because they are thought to have originated from the east coast of the USA. 

> According to wine historian [Edward Hyams](https://en.wikipedia.org/wiki/Edward_Hyams) and wine expert [Jancis Robinson](https://en.wikipedia.org/wiki/Jancis_Robinson),
> "_There is ample evidence that the labrusca was growing wild in North America before Europeans arrived._" 

The scientific name for these grapes is ["Vitis labrusca"](https://en.wikipedia.org/wiki/Vitis_labrusca), "Vitis" meaning grapevine and "labrusca" meaning "wild". Apparently these grapes are the closest thing to "wild" that we get in Europe now ... 

>Vitis labrusca are high in potassium, magnesium, folic acid e vitamin B6, flavonoids e **resveratrol**.
Ref: https://lifestyle.sapo.pt/saude/saude-e-medicina/artigos/uva-morangueira

Most city-folk - that have never picked a grape off a vine - have grown accustomed to seedless grapes so producers focus on them. 
I get it. Seeds are annoying. But genetically modified (or selectively bred) monoculture is worse. 
This last time we found the grapes for sale at the local market, I saved as many seeds as I could; **56**:

![image](https://github.com/dwyl/learn-permaculture/assets/194400/382eb13d-f0bf-4b98-bc1f-db732f3b33fa)

If even 10% of these seeds takes and we're able to plant out 5 vines it would be _more_ than "enough".
But however many sprout & survive is great. 

> If you're new to Grapes, it's a fascinating topic there are _hundreds_ of varieties: https://en.wikipedia.org/wiki/List_of_grape_varieties
> I don't drink wine so `while` I have superficial knowledge of varieties I don't deep dive into any I don't like.
> But some day I would love to do a grape-tasting with as many varieties as possible to see what I'm missing. 

# Todo

+ [x] Research how to grow grape vines from seed. 🔍 
+ [ ] Soak the seeds or sow them directly. 🌱 
+ [ ] Wait patiently and Tend to the seedlings for as long as it takes for them to transplantable into the ground! ⏳ 

This looks like a good starting point: https://www.wikihow.com/Grow-Grapes-from-Seeds

**Comment by nelsonic** [comment]
Looks like it's not the "right" time of the year to be doing this ... 🙃 

![image](https://github.com/dwyl/learn-permaculture/assets/194400/605cdb0a-0d04-40b4-a945-a05d962e040f)

Need to prepare the seeds by checking their viability.
Wash them in distilled water and then "stratify" them in the fridge over winter ... 🥶 

![stratify-seeds-over-winter](https://github.com/dwyl/learn-permaculture/assets/194400/6dc8e671-2aa4-4943-b6d1-a3a9538d09b8)

two to three months ... ⏳ 😮 
I recently saved a reusable (takeaway food) plastic container that is _perfect_ for this. 🍜 
So I'm going to spend **`T10m`** preparing the seeds _now_. 👌

**Comment by nelsonic** [comment]
Scratch that. It's a "no noise time" activity. Shelving it for when I can't make noise in the house! 👶 😴 ⌛
